# Site settings
title: vIdentity
email: feedback@videntity.de
description: >
  because your identity matters
baseurl: "/videntity.de/" # the subpath of your site, e.g. /blog/
url: "http://c-art.github.io" # the base hostname & protocol for your site

# Outputting
permalink: /:year/:month/:day/:title/index.html

# Build settings
markdown: kramdown
